# This workflow will deploy the project to AWS EC2

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: "ec2-3-1-206-9.ap-southeast-1.compute.amazonaws.com"
        REMOTE_USER: "ubuntu"
        TARGET: "/var/www/bojio-backend"

    - name: SSH into EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "ec2-3-1-206-9.ap-southeast-1.compute.amazonaws.com"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install Dependencies on EC2
      run: |
        echo test.txt
        sudo apt-get update
        pip3 install -r requirements.txt

    - name: Run Flask App
      run: |
        python3 app.py
